<?php
/** Create the approved NDT service-page hierarchy and substantive page copy. */

if (PHP_SAPI !== 'cli') { http_response_code(403); exit; }
$_SERVER['REQUEST_METHOD'] = 'CLI';
require '/var/www/html/wp-load.php';

$services = [
    'material-testing' => ['Material Testing', null, 'Material verification and field hardness services that help confirm alloy identity, condition and suitability before fabrication, installation or continued operation.', ['Alloy verification and material segregation', 'Incoming-material and warehouse checks', 'Fabrication, maintenance and shutdown support'], 'A traceable report records the test location, equipment, readings, material identification and applicable acceptance criteria.'],
    'pmi-xrf' => ['PMI – XRF', 'material-testing', 'Portable X-ray fluorescence provides rapid, nondestructive alloy screening by identifying many metallic elements and comparing the measured chemistry with the specified grade.', ['Stainless steels and nickel alloys', 'Piping, valves, fittings and weld consumables', 'Large-volume alloy verification programmes'], 'Results include measured elemental composition, grade indication and test-point identification. XRF limitations for light elements are stated in the report.'],
    'pmi-oes' => ['PMI – OES', 'material-testing', 'Optical emission spectroscopy supports alloy verification where measurement of lighter elements—particularly carbon—is important for distinguishing closely related steel grades.', ['Carbon and low-alloy steels', 'Carbon-equivalent and grade verification', 'Weld, piping and pressure-equipment material checks'], 'The report provides measured chemistry, identified test locations, equipment details and comparison with the requested material specification.'],
    'hardness-testing' => ['Hardness Testing', 'material-testing', 'Portable hardness testing evaluates material response to indentation and supports verification of heat treatment, weld condition and material consistency without removing the component.', ['Welds and heat-affected zones', 'Pressure equipment and piping', 'Forgings, castings and fabricated components'], 'Readings, locations, test method, conversion basis where applicable and acceptance criteria are documented.'],
    'telebrinell-comparator-bar' => ['Telebrinell Comparator Bar', 'hardness-testing', 'Telebrinell comparison testing uses a calibrated reference bar and controlled impact to compare indentation diameters for practical field hardness assessment of large components.', ['Large castings and forgings', 'Field locations with limited access', 'Maintenance and fabrication checks'], 'Reports identify the reference bar, indentation locations, measured diameters and calculated Brinell hardness values.'],
    'hydraulic-brinell' => ['Hydraulic Brinell', 'hardness-testing', 'Hydraulic Brinell testing applies a controlled load through a ball indenter, enabling direct hardness assessment on suitable components when conventional bench equipment is impractical.', ['Heavy components and forgings', 'Shop and field hardness verification', 'Quality-control and heat-treatment checks'], 'Recorded information includes applied load, indenter, dwell time, indentation measurement and reported hardness.'],
    'uci-hardness' => ['UCI Hardness', 'hardness-testing', 'Ultrasonic Contact Impedance testing measures the frequency shift of a vibrating probe under load, providing localized hardness readings with a small indentation.', ['Heat-affected zones and welds', 'Thin or small components', 'Hard-to-access inspection points'], 'The report identifies probe load, calibration, test locations, individual readings and any hardness-scale conversions.'],
    'surface-ndt' => ['Surface NDT', null, 'Surface nondestructive testing reveals discontinuities open to the surface or located just below it while keeping inspected components fit for service.', ['Weld inspection', 'Fabricated and machined components', 'Maintenance and in-service examinations'], 'Qualified personnel document preparation, technique, consumables, indications and evaluation against the specified code or procedure.'],
    'penetrant-testing' => ['Penetrant Testing', 'surface-ndt', 'Liquid penetrant testing uses visible or fluorescent penetrant to reveal surface-breaking discontinuities in clean, nonporous materials.', ['Nonferrous and ferrous components', 'Welds, castings and machined surfaces', 'Fine surface crack detection'], 'Reports cover surface preparation, penetrant system, dwell and development times, lighting conditions, indications and disposition.'],
    'magnetic-particle-testing' => ['Magnetic Particle Testing', 'surface-ndt', 'Magnetic particle testing magnetizes ferromagnetic material so flux leakage attracts visible or fluorescent particles at surface and near-surface discontinuities.', ['Carbon-steel welds and forgings', 'Crack detection around attachments', 'Fabrication and maintenance inspections'], 'The inspection record includes magnetization technique, field direction, consumables, lighting, indications and acceptance evaluation.'],
    'ultrasonic-testing' => ['Ultrasonic Testing', null, 'Ultrasonic testing introduces high-frequency sound into a component and evaluates returning signals to measure thickness or locate internal discontinuities.', ['Weld and base-material examination', 'Pressure equipment and structural components', 'Corrosion and remaining-wall assessment'], 'Calibrations, scan coverage, reference sensitivity, findings and evaluation are supplied in a traceable inspection report.'],
    'ultrasonic-thickness-gauging' => ['Ultrasonic Thickness Gauging', 'ultrasonic-testing', 'Ultrasonic thickness gauging measures remaining wall from one accessible surface, supporting corrosion monitoring without cutting or dismantling the component.', ['Pipes, tanks and pressure vessels', 'Corrosion circuits and condition surveys', 'Remaining-thickness trending'], 'Deliverables include location grids, readings, minimum thickness, calibration details and comparison with prior data when supplied.'],
    'conventional-ut' => ['Conventional UT', 'ultrasonic-testing', 'Conventional pulse-echo ultrasonic testing uses selected probes and calibrated sound paths to detect and characterize internal reflectors in welds and components.', ['Butt welds and structural joints', 'Forgings, plates and castings', 'Laminar and volumetric discontinuity checks'], 'The report states technique, probe, calibration block, scan coverage, reference level, detected indications and evaluation.'],
    'longitudinal-wave' => ['Longitudinal Wave', 'ultrasonic-testing', 'Straight-beam longitudinal-wave examination sends compressional sound normal to the surface for thickness measurement and detection of reflectors parallel to the entry surface.', ['Plate lamination checks', 'Forging and billet examination', 'Thickness and back-wall assessment'], 'Results document probe frequency, calibration range, scanning pattern, signal response and relevant indications.'],
    'shear-wave' => ['Shear Wave', 'ultrasonic-testing', 'Angle-beam shear-wave testing refracts sound through the component at a selected angle, making it effective for examining weld volumes and planar discontinuities.', ['Full-penetration weld inspection', 'Crack and lack-of-fusion detection', 'Nozzle, structural and piping welds'], 'Reports identify refracted angle, probe, calibration, scan plan, indication position and evaluation to the governing criteria.'],
    'advanced-ndt' => ['Advanced NDT', null, 'Advanced ultrasonic techniques combine encoded scanning, electronic beam control and digital data recording to improve coverage, repeatability and review of critical assets.', ['Critical weld examinations', 'Corrosion and degradation surveys', 'Baseline and in-service inspection programmes'], 'Data files, scan plans, calibration evidence, images and evaluated findings can be supplied according to the agreed inspection procedure.'],
    'paut' => ['PAUT', 'advanced-ndt', 'Phased Array Ultrasonic Testing electronically controls multiple probe elements to steer and focus sound beams, producing detailed views of welds and components.', ['Weld inspection and fabrication control', 'Complex geometries and restricted access', 'Encoded and repeatable examinations'], 'Deliverables can include setup files, sectorial or linear scans, encoded data, indication tables and an evaluation report.'],
    'tofd' => ['TOFD', 'advanced-ndt', 'Time of Flight Diffraction uses transmitter and receiver probes to detect diffracted signals from discontinuity tips, supporting accurate through-wall sizing.', ['Heavy-wall weld examination', 'Crack-height sizing', 'Code-compliant automated inspection plans'], 'Reports include calibration, scan coverage, TOFD images, location and sizing of relevant indications, and evaluation criteria.'],
    'corrosion-mapping' => ['Corrosion Mapping', 'advanced-ndt', 'Encoded ultrasonic corrosion mapping collects thickness readings over a defined grid to visualize wall loss and identify localized thinning.', ['Tanks, vessels and piping', 'Flow-accelerated corrosion surveys', 'Baseline and repeat condition monitoring'], 'The deliverable includes coverage maps, minimum readings, coordinate references, data files and areas recommended for engineering review.'],
    'visual-inspection' => ['Visual Inspection', null, 'Direct and remote visual inspection identifies visible surface conditions, workmanship issues and internal anomalies using controlled lighting and optical equipment.', ['Fabrication and weld examination', 'Internal component surveys', 'Maintenance, shutdown and condition assessment'], 'Inspection records include access conditions, equipment, image or video evidence, locations, observations and disposition.'],
    'video-borescope-inspection' => ['Video Borescope Inspection', 'visual-inspection', 'A flexible video borescope provides illuminated, magnified views inside equipment that cannot be assessed by direct line of sight.', ['Turbines, engines and rotating equipment', 'Heat exchangers and confined cavities', 'Internal weld and component examination'], 'Still images or video, probe route, observation locations and annotated findings are provided where the inspection scope permits.'],
    'internal-pipe-tube-inspection' => ['Internal Pipe/Tube Inspection', 'visual-inspection', 'Remote cameras and probes inspect internal pipe and tube surfaces for corrosion, deposits, damage, obstructions and visible fabrication conditions.', ['Process piping and drains', 'Heat-exchanger and boiler tubes', 'New-construction cleanliness checks'], 'Reports provide inspected length, access point, orientation, image evidence, observed conditions and inaccessible areas.'],
    'full-hd-long-distance-camera-inspection' => ['Full HD Long-Distance Camera Inspection', 'internal-pipe-tube-inspection', 'Full-HD long-distance camera systems support remote visual surveys through extended pipe runs, ducts, tanks and other areas where personnel entry is restricted or undesirable.', ['Long pipe and duct runs', 'Large vessels and inaccessible spaces', 'Foreign-object, blockage and condition surveys'], 'Recorded video and still images are indexed to the inspection route, with observations, approximate locations and access limitations documented.'],
];

$ids = [];
foreach ($services as $slug => [$title, $parent_slug]) {
    $existing = get_page_by_path($slug, OBJECT, 'page');
    if ($existing) $ids[$slug] = (int) $existing->ID;
}

$pending = $services;
while ($pending) {
    $progress = false;
    foreach ($pending as $slug => $service) {
        [$title, $parent_slug, $lead, $applications, $deliverable] = $service;
        if ($parent_slug && empty($ids[$parent_slug])) continue;
        $parent_id = $parent_slug ? $ids[$parent_slug] : 0;
        $children = [];
        foreach ($services as $child_slug => $child) if (($child[1] ?? null) === $slug) $children[$child_slug] = $child[0];
        $scope_items = $children ?: $applications;
        $scope = '';
        foreach ($scope_items as $key => $label) {
            $text = is_string($key) ? '<a href="' . esc_url(home_url('/' . ($parent_slug ? $parent_slug . '/' : '') . $slug . '/' . $key . '/')) . '">' . esc_html($label) . '</a>' : esc_html($label);
            $scope .= '<li>' . $text . '</li>';
        }
        $content = '<main class="gripco-service"><div class="gripco-service__eyebrow">Gripco Inspection Services</div><h1>' . esc_html($title) . '</h1><p class="gripco-service__lead">' . esc_html($lead) . '</p><div class="gripco-service__grid"><section class="gripco-service__card"><h2>Service scope</h2><ul>' . $scope . '</ul></section><section class="gripco-service__card"><h2>Inspection approach</h2><p>Gripco plans the work around the component, material, access conditions and required acceptance standard. Equipment checks and calibration are completed before examination, and relevant indications are evaluated by qualified personnel under the approved procedure.</p></section><section class="gripco-service__card"><h2>Typical applications</h2><ul>';
        foreach ($applications as $application) $content .= '<li>' . esc_html($application) . '</li>';
        $content .= '</ul></section><section class="gripco-service__card"><h2>Reporting</h2><p>' . esc_html($deliverable) . '</p></section></div><section class="gripco-service__cta"><h2>Discuss your inspection requirement</h2><p>Contact Gripco with the component, material, applicable code, inspection stage and site conditions so we can propose the appropriate technique and coverage.</p></section></main>';
        $post = ['post_title'=>$title,'post_name'=>$slug,'post_parent'=>$parent_id,'post_type'=>'page','post_status'=>'publish','post_content'=>$content,'post_excerpt'=>$lead];
        if (!empty($ids[$slug])) { $post['ID']=$ids[$slug]; $id=wp_update_post($post,true); } else { $id=wp_insert_post($post,true); }
        if (is_wp_error($id)) { fwrite(STDERR, "$slug: {$id->get_error_message()}\n"); exit(1); }
        update_post_meta($id, '_gripco_service_catalogue', 1);
        $ids[$slug]=(int)$id; unset($pending[$slug]); $progress=true;
    }
    if (!$progress) { fwrite(STDERR,"Unresolved page hierarchy.\n"); exit(1); }
}

echo 'Created or updated ' . count($ids) . " NDT service pages.\n";
